// Generated by Framer (d31cd55)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    SVG,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import * as localizedValues from "./V1oZgUIZe-0.js";
const cycleOrder = ["q3xZWtCz3", "wbs4kEBcS"];
const serializationHash = "framer-pMs89";
const variantClassNames = {
    q3xZWtCz3: "framer-v-1t5qjy0",
    wbs4kEBcS: "framer-v-1v8kaew"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants === null || variants === void 0 ? void 0 : variants.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const valuesByLocaleId = {
    xBEfqdO_2: localizedValues
};
const getLocalizedValue = (key, locale) => {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) {
                return value;
            }
        }
        locale = locale.fallback;
    }
};
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value !== null && value !== void 0 ? value : config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion(React.Fragment);
const humanReadableVariantMap = {
    Left: "q3xZWtCz3",
    Right: "wbs4kEBcS"
};
const getProps = ({
    borderColor,
    color,
    height,
    id,
    width,
    ...props
}) => {
    var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2;
    return { ...props,
        IfOylP2jC: (_ref = borderColor !== null && borderColor !== void 0 ? borderColor : props.IfOylP2jC) !== null && _ref !== void 0 ? _ref : {
            borderColor: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
            borderStyle: "solid",
            borderWidth: 2
        },
        uSS3wjZ48: (_ref1 = color !== null && color !== void 0 ? color : props.uSS3wjZ48) !== null && _ref1 !== void 0 ? _ref1 : "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
        variant: (_ref2 = (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null && _humanReadableVariantMap_props_variant !== void 0 ? _humanReadableVariantMap_props_variant : props.variant) !== null && _ref2 !== void 0 ? _ref2 : "q3xZWtCz3"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        IfOylP2jC,
        uSS3wjZ48,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "q3xZWtCz3",
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const sharedStyleClassNames = [];
    const componentViewport = useComponentViewport();
    var _IfOylP2jC_borderBottomWidth, _IfOylP2jC_borderLeftWidth, _IfOylP2jC_borderRightWidth, _IfOylP2jC_borderTopWidth;
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(serializationHash, ...sharedStyleClassNames, "framer-1t5qjy0", className, classNames),
                    "data-border": true,
                    "data-framer-name": "Left",
                    layoutDependency: layoutDependency,
                    layoutId: "q3xZWtCz3",
                    ref: ref !== null && ref !== void 0 ? ref : ref1,
                    style: {
                        "--border-bottom-width": "2px",
                        "--border-color": "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
                        "--border-left-width": "2px",
                        "--border-right-width": "2px",
                        "--border-style": "solid",
                        "--border-top-width": "2px",
                        borderBottomLeftRadius: 999,
                        borderBottomRightRadius: 999,
                        borderTopLeftRadius: 999,
                        borderTopRightRadius: 999,
                        ...style
                    },
                    variants: {
                        wbs4kEBcS: {
                            "--border-bottom-width": `${(_IfOylP2jC_borderBottomWidth=IfOylP2jC.borderBottomWidth)!==null&&_IfOylP2jC_borderBottomWidth!==void 0?_IfOylP2jC_borderBottomWidth:IfOylP2jC.borderWidth}px`,
                            "--border-color": IfOylP2jC.borderColor,
                            "--border-left-width": `${(_IfOylP2jC_borderLeftWidth=IfOylP2jC.borderLeftWidth)!==null&&_IfOylP2jC_borderLeftWidth!==void 0?_IfOylP2jC_borderLeftWidth:IfOylP2jC.borderWidth}px`,
                            "--border-right-width": `${(_IfOylP2jC_borderRightWidth=IfOylP2jC.borderRightWidth)!==null&&_IfOylP2jC_borderRightWidth!==void 0?_IfOylP2jC_borderRightWidth:IfOylP2jC.borderWidth}px`,
                            "--border-style": IfOylP2jC.borderStyle,
                            "--border-top-width": `${(_IfOylP2jC_borderTopWidth=IfOylP2jC.borderTopWidth)!==null&&_IfOylP2jC_borderTopWidth!==void 0?_IfOylP2jC_borderTopWidth:IfOylP2jC.borderWidth}px`
                        }
                    },
                    ...addPropertyOverrides({
                        wbs4kEBcS: {
                            "data-framer-name": "Right"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-4918pb",
                        layoutDependency: layoutDependency,
                        layoutId: "aWyLx6Rsa",
                        style: {
                            rotateY: 180
                        },
                        variants: {
                            wbs4kEBcS: {
                                rotateY: 0
                            }
                        },
                        children: /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-1c4sdwa",
                            "data-framer-name": "icons_arrow",
                            fill: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
                            intrinsicHeight: 24,
                            intrinsicWidth: 24,
                            layoutDependency: layoutDependency,
                            layoutId: "GdqXGrcCi",
                            svg: '<svg width="24" height="24" xmlns="http://www.w3.org/2000/svg"><path d="m20.566 10.917.053.058a.97.97 0 0 1 .043.051l-.096-.109A1.545 1.545 0 0 1 21 11.99v.02a1.588 1.588 0 0 1-.248.838 1.506 1.506 0 0 1-.186.235l.096-.11a1.541 1.541 0 0 1-.044.053l-.052.057-.014.014-6.389 6.459a1.48 1.48 0 0 1-2.128-.014 1.568 1.568 0 0 1 .013-2.18l3.779-3.82H4.505C3.674 13.541 3 12.851 3 12c0-.851.674-1.541 1.505-1.541h11.322l-3.779-3.82a1.569 1.569 0 0 1-.116-2.063l.103-.118a1.48 1.48 0 0 1 2.128-.014l6.39 6.46.013.013z" fill-rule="evenodd"/></svg>',
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                wbs4kEBcS: {
                                    fill: uSS3wjZ48
                                }
                            }, baseVariant, gestureVariant)
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-pMs89.framer-188leka, .framer-pMs89 .framer-188leka { display: block; }", ".framer-pMs89.framer-1t5qjy0 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-pMs89 .framer-4918pb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-pMs89 .framer-1c4sdwa { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-pMs89.framer-1t5qjy0, .framer-pMs89 .framer-4918pb { gap: 0px; } .framer-pMs89.framer-1t5qjy0 > *, .framer-pMs89 .framer-4918pb > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-pMs89.framer-1t5qjy0 > :first-child, .framer-pMs89 .framer-4918pb > :first-child { margin-left: 0px; } .framer-pMs89.framer-1t5qjy0 > :last-child, .framer-pMs89 .framer-4918pb > :last-child { margin-right: 0px; } }", '.framer-pMs89[data-border="true"]::after, .framer-pMs89 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 40
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"wbs4kEBcS":{"layout":["auto","auto"]}}}
 * @framerVariables {"IfOylP2jC":"borderColor","uSS3wjZ48":"color"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerV1oZgUIZe = withCSS(Component, css, "framer-pMs89");
export default FramerV1oZgUIZe;
FramerV1oZgUIZe.displayName = "Shared elements/Cursor";
FramerV1oZgUIZe.defaultProps = {
    height: 40,
    width: 40
};
addPropertyControls(FramerV1oZgUIZe, {
    variant: {
        options: ["q3xZWtCz3", "wbs4kEBcS"],
        optionTitles: ["Left", "Right"],
        title: "Variant",
        type: ControlType.Enum
    },
    IfOylP2jC: {
        defaultValue: {
            borderColor: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
            borderStyle: "solid",
            borderWidth: 2
        },
        title: "border color",
        type: ControlType.Border
    },
    uSS3wjZ48: {
        defaultValue: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
        title: "color",
        type: ControlType.Color
    }
});
addFonts(FramerV1oZgUIZe, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerV1oZgUIZe",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"IfOylP2jC\":\"borderColor\",\"uSS3wjZ48\":\"color\"}",
                "framerIntrinsicHeight": "40",
                "framerIntrinsicWidth": "40",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"wbs4kEBcS\":{\"layout\":[\"auto\",\"auto\"]}}}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./V1oZgUIZe.map