// Generated by Framer (518403a)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getPropertyControls,
    Link,
    RichText,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import {
    Icon as Material
} from "https://framerusercontent.com/modules/6Ldpz1V0DkD45gXvi67I/PCgBX5d6MdQT7E7nhdXn/Material.js";
const MaterialFonts = getFonts(Material);
const MaterialControls = getPropertyControls(Material);
const enabledGestures = {
    kd9T5umXp: {
        hover: true
    },
    oHk1n4u3M: {
        hover: true
    },
    oPaSIUBs4: {
        hover: true
    }
};
const cycleOrder = ["kd9T5umXp", "oPaSIUBs4", "oHk1n4u3M", "gty4zGxTh", "IGqccGXEP", "tNdKiEME4"];
const serializationHash = "framer-lt4fp";
const variantClassNames = {
    gty4zGxTh: "framer-v-160xi0",
    IGqccGXEP: "framer-v-aypb8o",
    kd9T5umXp: "framer-v-6boy5h",
    oHk1n4u3M: "framer-v-llypcg",
    oPaSIUBs4: "framer-v-71dggv",
    tNdKiEME4: "framer-v-1yhpssk"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const LK2XHiWHO = undefined;
const ASYaGj8Uo = undefined;
const daId8sPMQ = undefined;
const jyNzkH0KX = undefined;
const x60flyUYG = undefined;
const covLl01nh = undefined;
const TCMFuh1ns = undefined;
const zkh2gB29G = undefined;
const Lr1zEVmWc = undefined;
const ZvRIBOrCl = undefined;
const EWzxxLsSp = undefined;
const rKrzPjwMV = undefined;
const ZotahwTRM = undefined;
const transition1 = {
    duration: 0,
    type: "tween"
};
const convertFromBoolean = (value, activeLocale, {
    EWzxxLsSp
}) => {
    return value ? EWzxxLsSp : "";
};
const toString = value => {
    return typeof value === "string" ? value : String(value);
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    "Large - blue - hover": "IGqccGXEP",
    "Large - blue": "gty4zGxTh",
    "Large - no icon": "kd9T5umXp",
    "Large - with icon": "oPaSIUBs4",
    "Small - no icon": "tNdKiEME4",
    "Small - with icon": "oHk1n4u3M"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    buttonColor,
    click,
    height,
    hoverColor,
    icon,
    iconColor,
    id,
    label,
    link,
    newTab,
    tap2,
    tap3,
    tap4,
    textColor,
    vISible,
    width,
    ...props
}) => {
    return { ...props,
        ASYaGj8Uo: tap2 ? ? props.ASYaGj8Uo,
        covLl01nh: link ? ? props.covLl01nh,
        daId8sPMQ: tap3 ? ? props.daId8sPMQ,
        EWzxxLsSp: label ? ? props.EWzxxLsSp ? ? "Button",
        jyNzkH0KX: tap4 ? ? props.jyNzkH0KX,
        LK2XHiWHO: buttonColor ? ? props.LK2XHiWHO ? ? "var(--token-b7b4f0e8-9795-4dc5-bdb6-a2c39c44f19c, rgb(48, 181, 102))",
        Lr1zEVmWc: textColor ? ? props.Lr1zEVmWc ? ? "rgb(255, 255, 255)",
        rKrzPjwMV: iconColor ? ? props.rKrzPjwMV ? ? "rgb(255, 255, 255)",
        TCMFuh1ns: newTab ? ? props.TCMFuh1ns,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "kd9T5umXp",
        x60flyUYG: click ? ? props.x60flyUYG,
        zkh2gB29G: hoverColor ? ? props.zkh2gB29G ? ? "var(--token-09796d70-9aeb-4ed6-8b33-a3ab9c2aadd1, rgb(37, 141, 80))",
        ZotahwTRM: icon ? ? props.ZotahwTRM ? ? "Email",
        ZvRIBOrCl: vISible ? ? props.ZvRIBOrCl ? ? true
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        covLl01nh,
        EWzxxLsSp,
        ZvRIBOrCl,
        LK2XHiWHO,
        ASYaGj8Uo,
        daId8sPMQ,
        jyNzkH0KX,
        zkh2gB29G,
        x60flyUYG,
        TCMFuh1ns,
        ZotahwTRM,
        Lr1zEVmWc,
        rKrzPjwMV,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "kd9T5umXp",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTapi6fjde = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (ASYaGj8Uo) {
            const res = await ASYaGj8Uo(...args);
            if (res === false) return false;
        }
        if (daId8sPMQ) {
            const res = await daId8sPMQ(...args);
            if (res === false) return false;
        }
        if (jyNzkH0KX) {
            const res = await jyNzkH0KX(...args);
            if (res === false) return false;
        }
        if (x60flyUYG) {
            const res = await x60flyUYG(...args);
            if (res === false) return false;
        }
    });
    const onMouseEntervpecnd = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: true
        });
        setVariant("IGqccGXEP");
    });
    const onMouseLeave10v525j = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: false
        });
        setVariant("gty4zGxTh");
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const textContent = toString(convertFromBoolean(ZvRIBOrCl, activeLocale, {
        EWzxxLsSp
    }));
    const isDisplayed = () => {
        if (["oPaSIUBs4-hover", "oHk1n4u3M-hover"].includes(gestureVariant)) return true;
        if (["oPaSIUBs4", "oHk1n4u3M"].includes(baseVariant)) return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: covLl01nh,
                    motionChild: true,
                    nodeId: "kd9T5umXp",
                    openInNewTab: TCMFuh1ns,
                    scopeId: "Tfa5J19JL",
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-6boy5h",className,classNames)} framer-1k0chnt`,
                        "data-framer-name": "Large - no icon",
                        "data-highlight": true,
                        "data-reset": "button",
                        layoutDependency: layoutDependency,
                        layoutId: "kd9T5umXp",
                        onTap: onTapi6fjde,
                        ref: refBinding,
                        style: {
                            backgroundColor: LK2XHiWHO,
                            borderBottomLeftRadius: 32,
                            borderBottomRightRadius: 32,
                            borderTopLeftRadius: 32,
                            borderTopRightRadius: 32,
                            ...style
                        },
                        variants: {
                            "kd9T5umXp-hover": {
                                backgroundColor: zkh2gB29G
                            },
                            "oHk1n4u3M-hover": {
                                backgroundColor: zkh2gB29G
                            },
                            "oPaSIUBs4-hover": {
                                backgroundColor: "var(--token-09796d70-9aeb-4ed6-8b33-a3ab9c2aadd1, rgb(37, 141, 80))"
                            }
                        },
                        ...addPropertyOverrides({
                            "kd9T5umXp-hover": {
                                "data-framer-name": undefined
                            },
                            "oHk1n4u3M-hover": {
                                "data-framer-name": undefined
                            },
                            "oPaSIUBs4-hover": {
                                "data-framer-name": undefined
                            },
                            gty4zGxTh: {
                                "data-framer-name": "Large - blue",
                                onMouseEnter: onMouseEntervpecnd
                            },
                            IGqccGXEP: {
                                "data-framer-name": "Large - blue - hover",
                                onMouseLeave: onMouseLeave10v525j
                            },
                            oHk1n4u3M: {
                                "data-framer-name": "Small - with icon"
                            },
                            oPaSIUBs4: {
                                "data-framer-name": "Large - with icon"
                            },
                            tNdKiEME4: {
                                "data-framer-name": "Small - no icon",
                                "data-highlight": undefined,
                                onTap: undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    dir: "auto",
                                    style: {
                                        "--font-selector": "Q1VTVE9NVjI7UHVmZmluIFRyYW5zaXQgQm9sZA==",
                                        "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                        "--framer-font-size": "18px",
                                        "--framer-font-weight": "700",
                                        "--framer-line-height": "1em",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-Lr1zEVmWc-Tfa5J19JL))"
                                    },
                                    children: "Button"
                                })
                            }),
                            className: "framer-1em31oc",
                            fonts: ["CUSTOMV2;Puffin Transit Bold"],
                            layoutDependency: layoutDependency,
                            layoutId: "QiEZtPeT9",
                            style: {
                                "--extracted-r6o4lv": "var(--variable-reference-Lr1zEVmWc-Tfa5J19JL)",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                                "--variable-reference-Lr1zEVmWc-Tfa5J19JL": Lr1zEVmWc
                            },
                            text: textContent,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                oHk1n4u3M: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            dir: "auto",
                                            style: {
                                                "--font-selector": "Q1VTVE9NVjI7UHVmZmluIFRyYW5zaXQgQm9sZA==",
                                                "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                                "--framer-font-weight": "700",
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-Lr1zEVmWc-Tfa5J19JL))"
                                            },
                                            children: "Button"
                                        })
                                    })
                                },
                                tNdKiEME4: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            dir: "auto",
                                            style: {
                                                "--font-selector": "Q1VTVE9NVjI7UHVmZmluIFRyYW5zaXQgQm9sZA==",
                                                "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                                "--framer-font-size": "14px",
                                                "--framer-font-weight": "700",
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-Lr1zEVmWc-Tfa5J19JL))"
                                            },
                                            children: "Button"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), isDisplayed() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-177wt3e-container",
                                isAuthoredByUser: true,
                                isModuleExternal: true,
                                layoutDependency: layoutDependency,
                                layoutId: "IgD3cFjB4-container",
                                nodeId: "IgD3cFjB4",
                                rendersWithMotion: true,
                                scopeId: "Tfa5J19JL",
                                children: /*#__PURE__*/ _jsx(Material, {
                                    color: rKrzPjwMV,
                                    height: "100%",
                                    iconSearch: "Home",
                                    iconSelection: "PhoneIphone",
                                    iconStyle15: "Filled",
                                    iconStyle2: "Filled",
                                    iconStyle7: "Filled",
                                    id: "IgD3cFjB4",
                                    layoutId: "IgD3cFjB4",
                                    mirrored: false,
                                    selectByList: true,
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        oHk1n4u3M: {
                                            iconSelection: ZotahwTRM
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        }), /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-1u7l25g",
                            layoutDependency: layoutDependency,
                            layoutId: "FAKjPNoDZ",
                            style: {
                                background: "radial-gradient(85.2% 100% at 50% 0%, rgba(255, 255, 255, 0.16) 0%, rgba(0, 0, 0, 0) 100%)",
                                borderBottomLeftRadius: 49,
                                borderBottomRightRadius: 49,
                                borderTopLeftRadius: 49,
                                borderTopRightRadius: 49
                            }
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-lt4fp.framer-1k0chnt, .framer-lt4fp .framer-1k0chnt { display: block; }", ".framer-lt4fp.framer-6boy5h { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 56px; justify-content: center; padding: 16px 24px 16px 24px; position: relative; text-decoration: none; width: min-content; }", ".framer-lt4fp .framer-1em31oc { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-lt4fp .framer-177wt3e-container { flex: none; height: 32px; position: relative; width: 32px; }", ".framer-lt4fp .framer-1u7l25g { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); z-index: 1; }", ".framer-lt4fp.framer-v-71dggv.framer-6boy5h { padding: 0px 24px 0px 24px; }", ".framer-lt4fp.framer-v-llypcg.framer-6boy5h { gap: 4px; height: 48px; padding: 0px 16px 0px 16px; }", ".framer-lt4fp.framer-v-llypcg .framer-177wt3e-container { height: 24px; width: 24px; }", ".framer-lt4fp.framer-v-1yhpssk.framer-6boy5h { gap: 4px; height: 48px; padding: 0px 24px 0px 24px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 56
 * @framerIntrinsicWidth 110
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"oPaSIUBs4":{"layout":["auto","fixed"]},"oHk1n4u3M":{"layout":["auto","fixed"]},"gty4zGxTh":{"layout":["auto","fixed"]},"IGqccGXEP":{"layout":["auto","fixed"]},"tNdKiEME4":{"layout":["auto","fixed"]},"Oqo2DgbEp":{"layout":["auto","fixed"]},"L4JjVTJjR":{"layout":["auto","fixed"]},"UCOFzg3Oq":{"layout":["auto","fixed"]}}}
 * @framerVariables {"covLl01nh":"link","EWzxxLsSp":"label","ZvRIBOrCl":"vISible","LK2XHiWHO":"buttonColor","ASYaGj8Uo":"tap2","daId8sPMQ":"tap3","jyNzkH0KX":"tap4","zkh2gB29G":"hoverColor","x60flyUYG":"click","TCMFuh1ns":"newTab","ZotahwTRM":"icon","Lr1zEVmWc":"textColor","rKrzPjwMV":"iconColor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerTfa5J19JL = withCSS(Component, css, "framer-lt4fp");
export default FramerTfa5J19JL;
FramerTfa5J19JL.displayName = "Call to action/Primary button";
FramerTfa5J19JL.defaultProps = {
    height: 56,
    width: 110
};
addPropertyControls(FramerTfa5J19JL, {
    variant: {
        options: ["kd9T5umXp", "oPaSIUBs4", "oHk1n4u3M", "gty4zGxTh", "IGqccGXEP", "tNdKiEME4"],
        optionTitles: ["Large - no icon", "Large - with icon", "Small - with icon", "Large - blue", "Large - blue - hover", "Small - no icon"],
        title: "Variant",
        type: ControlType.Enum
    },
    covLl01nh: {
        title: "Link",
        type: ControlType.Link
    },
    EWzxxLsSp: {
        defaultValue: "Button",
        placeholder: "Button",
        title: "Label",
        type: ControlType.String
    },
    ZvRIBOrCl: {
        defaultValue: true,
        title: "VIsible",
        type: ControlType.Boolean
    },
    LK2XHiWHO: {
        defaultValue: 'var(--token-b7b4f0e8-9795-4dc5-bdb6-a2c39c44f19c, rgb(48, 181, 102)) /* {"name":"Green/500"} */',
        title: "Button color",
        type: ControlType.Color
    },
    ASYaGj8Uo: {
        title: "Tap 2",
        type: ControlType.EventHandler
    },
    daId8sPMQ: {
        title: "Tap 3",
        type: ControlType.EventHandler
    },
    jyNzkH0KX: {
        title: "Tap 4",
        type: ControlType.EventHandler
    },
    zkh2gB29G: {
        defaultValue: 'var(--token-09796d70-9aeb-4ed6-8b33-a3ab9c2aadd1, rgb(37, 141, 80)) /* {"name":"Green/600"} */',
        title: "Hover color",
        type: ControlType.Color
    },
    x60flyUYG: {
        title: "Click",
        type: ControlType.EventHandler
    },
    TCMFuh1ns: {
        defaultValue: false,
        title: "New Tab",
        type: ControlType.Boolean
    },
    ZotahwTRM: MaterialControls ? .["iconSelection"] && { ...MaterialControls["iconSelection"],
        defaultValue: "Email",
        description: undefined,
        hidden: undefined,
        title: "icon"
    },
    Lr1zEVmWc: {
        defaultValue: "rgb(255, 255, 255)",
        title: "Text color",
        type: ControlType.Color
    },
    rKrzPjwMV: {
        defaultValue: "rgb(255, 255, 255)",
        title: "Icon color",
        type: ControlType.Color
    }
});
addFonts(FramerTfa5J19JL, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Puffin Transit Bold",
        source: "custom",
        style: "normal",
        uiFamilyName: "Puffin Transit",
        url: "https://framerusercontent.com/assets/GkunKxYt8QgoE68Kh0hyMBJoSI.ttf",
        weight: "700"
    }]
}, ...MaterialFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerTfa5J19JL",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"fixed\"]},\"oPaSIUBs4\":{\"layout\":[\"auto\",\"fixed\"]},\"oHk1n4u3M\":{\"layout\":[\"auto\",\"fixed\"]},\"gty4zGxTh\":{\"layout\":[\"auto\",\"fixed\"]},\"IGqccGXEP\":{\"layout\":[\"auto\",\"fixed\"]},\"tNdKiEME4\":{\"layout\":[\"auto\",\"fixed\"]},\"Oqo2DgbEp\":{\"layout\":[\"auto\",\"fixed\"]},\"L4JjVTJjR\":{\"layout\":[\"auto\",\"fixed\"]},\"UCOFzg3Oq\":{\"layout\":[\"auto\",\"fixed\"]}}}",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "110",
                "framerVariables": "{\"covLl01nh\":\"link\",\"EWzxxLsSp\":\"label\",\"ZvRIBOrCl\":\"vISible\",\"LK2XHiWHO\":\"buttonColor\",\"ASYaGj8Uo\":\"tap2\",\"daId8sPMQ\":\"tap3\",\"jyNzkH0KX\":\"tap4\",\"zkh2gB29G\":\"hoverColor\",\"x60flyUYG\":\"click\",\"TCMFuh1ns\":\"newTab\",\"ZotahwTRM\":\"icon\",\"Lr1zEVmWc\":\"textColor\",\"rKrzPjwMV\":\"iconColor\"}",
                "framerIntrinsicHeight": "56"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./Tfa5J19JL.map