// Generated by Framer (ba156f5)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getPropertyControls,
    Link,
    RichText,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import {
    Icon as Material
} from "https://framerusercontent.com/modules/P6iRmn2E7YfqeskvGgOk/d6cfpw6fcGn0pHynMMH7/Material.js";
const MaterialFonts = getFonts(Material);
const MaterialControls = getPropertyControls(Material);
const enabledGestures = {
    EqKZSVRcz: {
        hover: true
    },
    JIQlmXG3E: {
        hover: true,
        pressed: true
    },
    LmeK3DXy0: {
        hover: true,
        pressed: true
    },
    oc6EpmQ93: {
        hover: true
    },
    SaF3AtRH2: {
        hover: true,
        pressed: true
    }
};
const cycleOrder = ["SaF3AtRH2", "JIQlmXG3E", "LmeK3DXy0", "EqKZSVRcz", "oc6EpmQ93", "jpYVtlPvM", "bToTb8PWg"];
const serializationHash = "framer-DRr9G";
const variantClassNames = {
    bToTb8PWg: "framer-v-1gdfkb6",
    EqKZSVRcz: "framer-v-7frf60",
    JIQlmXG3E: "framer-v-u1rd9y",
    jpYVtlPvM: "framer-v-1f9gcuc",
    LmeK3DXy0: "framer-v-zd7s7d",
    oc6EpmQ93: "framer-v-o64xxn",
    SaF3AtRH2: "framer-v-s3svbn"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    duration: 0,
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "BIg button": "oc6EpmQ93",
    "Icon only - hover": "bToTb8PWg",
    "Icon only": "jpYVtlPvM",
    "Large - no icon": "SaF3AtRH2",
    "Large - with icon": "JIQlmXG3E",
    "Small - no icon": "EqKZSVRcz",
    "Small - with icon": "LmeK3DXy0"
};
const getProps = ({
    backgroundColor,
    borderColor,
    buttonLink,
    buttonName,
    height,
    hoverColor,
    icon,
    iconColor,
    id,
    newTab,
    pressedColor,
    textColor,
    width,
    ...props
}) => {
    return { ...props,
        Bc1xkt19v: pressedColor ? ? props.Bc1xkt19v ? ? "var(--token-0ef7fac7-2c02-40a6-9e44-9c2300205686, rgb(10, 41, 23))",
        covLl01nh: buttonLink ? ? props.covLl01nh,
        EWzxxLsSp: buttonName ? ? props.EWzxxLsSp ? ? "Button",
        F_7_e4f0K: icon ? ? props.F_7_e4f0K ? ? "Close",
        Gu0ypBZYc: backgroundColor ? ? props.Gu0ypBZYc ? ? "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
        LBCylfD1Z: borderColor ? ? props.LBCylfD1Z ? ? {
            borderColor: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
            borderStyle: "solid",
            borderWidth: 2
        },
        NdU_7bDFg: hoverColor ? ? props.NdU_7bDFg ? ? "rgb(18, 69, 43)",
        p7ZsoTYh9: newTab ? ? props.p7ZsoTYh9,
        Psd861PGB: iconColor ? ? props.Psd861PGB ? ? "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
        qicr92Taf: textColor ? ? props.qicr92Taf ? ? "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "SaF3AtRH2"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        covLl01nh,
        EWzxxLsSp,
        p7ZsoTYh9,
        qicr92Taf,
        LBCylfD1Z,
        NdU_7bDFg,
        Bc1xkt19v,
        Gu0ypBZYc,
        Psd861PGB,
        F_7_e4f0K,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "SaF3AtRH2",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onMouseEntery74jci = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: true
        });
        setVariant("bToTb8PWg");
    });
    const onMouseLeaveqpjrr2 = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: false
        });
        setVariant("jpYVtlPvM");
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (["jpYVtlPvM", "bToTb8PWg"].includes(baseVariant)) return false;
        return true;
    };
    const isDisplayed1 = () => {
        if (["JIQlmXG3E-hover", "JIQlmXG3E-pressed", "LmeK3DXy0-hover", "LmeK3DXy0-pressed", "oc6EpmQ93-hover"].includes(gestureVariant)) return true;
        if (["JIQlmXG3E", "LmeK3DXy0", "oc6EpmQ93", "jpYVtlPvM", "bToTb8PWg"].includes(baseVariant)) return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: covLl01nh,
                    motionChild: true,
                    nodeId: "SaF3AtRH2",
                    openInNewTab: p7ZsoTYh9,
                    scopeId: "BAdt6St43",
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-s3svbn",className,classNames)} framer-v5zt70`,
                        "data-border": true,
                        "data-framer-name": "Large - no icon",
                        "data-reset": "button",
                        layoutDependency: layoutDependency,
                        layoutId: "SaF3AtRH2",
                        ref: refBinding,
                        style: {
                            "--border-bottom-width": (LBCylfD1Z.borderBottomWidth ? ? LBCylfD1Z.borderWidth) + "px",
                            "--border-color": LBCylfD1Z.borderColor,
                            "--border-left-width": (LBCylfD1Z.borderLeftWidth ? ? LBCylfD1Z.borderWidth) + "px",
                            "--border-right-width": (LBCylfD1Z.borderRightWidth ? ? LBCylfD1Z.borderWidth) + "px",
                            "--border-style": LBCylfD1Z.borderStyle,
                            "--border-top-width": (LBCylfD1Z.borderTopWidth ? ? LBCylfD1Z.borderWidth) + "px",
                            backgroundColor: "rgba(0, 0, 0, 0)",
                            borderBottomLeftRadius: 32,
                            borderBottomRightRadius: 32,
                            borderTopLeftRadius: 32,
                            borderTopRightRadius: 32,
                            ...style
                        },
                        variants: {
                            "EqKZSVRcz-hover": {
                                backgroundColor: Gu0ypBZYc
                            },
                            "JIQlmXG3E-hover": {
                                backgroundColor: "rgba(0, 0, 0, 0)"
                            },
                            "JIQlmXG3E-pressed": {
                                backgroundColor: "rgba(0, 0, 0, 0)"
                            },
                            "LmeK3DXy0-hover": {
                                backgroundColor: "rgba(0, 0, 0, 0)"
                            },
                            "LmeK3DXy0-pressed": {
                                backgroundColor: "rgba(0, 0, 0, 0)"
                            },
                            "oc6EpmQ93-hover": {
                                "--border-bottom-width": "0px",
                                "--border-color": "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
                                "--border-left-width": "0px",
                                "--border-right-width": "0px",
                                "--border-style": "solid",
                                "--border-top-width": "0px",
                                backgroundColor: NdU_7bDFg
                            },
                            "SaF3AtRH2-hover": {
                                backgroundColor: NdU_7bDFg
                            },
                            "SaF3AtRH2-pressed": {
                                backgroundColor: Bc1xkt19v
                            },
                            bToTb8PWg: {
                                backgroundColor: NdU_7bDFg
                            },
                            JIQlmXG3E: {
                                "--border-bottom-width": "2px",
                                "--border-color": "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
                                "--border-left-width": "2px",
                                "--border-right-width": "2px",
                                "--border-style": "solid",
                                "--border-top-width": "2px"
                            },
                            LmeK3DXy0: {
                                "--border-bottom-width": "2px",
                                "--border-color": "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
                                "--border-left-width": "2px",
                                "--border-right-width": "2px",
                                "--border-style": "solid",
                                "--border-top-width": "2px"
                            },
                            oc6EpmQ93: {
                                borderBottomLeftRadius: 40,
                                borderBottomRightRadius: 40,
                                borderTopLeftRadius: 40,
                                borderTopRightRadius: 40
                            }
                        },
                        ...addPropertyOverrides({
                            "EqKZSVRcz-hover": {
                                "data-framer-name": undefined
                            },
                            "JIQlmXG3E-hover": {
                                "data-framer-name": undefined
                            },
                            "JIQlmXG3E-pressed": {
                                "data-framer-name": undefined
                            },
                            "LmeK3DXy0-hover": {
                                "data-framer-name": undefined
                            },
                            "LmeK3DXy0-pressed": {
                                "data-framer-name": undefined
                            },
                            "oc6EpmQ93-hover": {
                                "data-framer-name": undefined
                            },
                            "SaF3AtRH2-hover": {
                                "data-framer-name": undefined
                            },
                            "SaF3AtRH2-pressed": {
                                "data-framer-name": undefined
                            },
                            bToTb8PWg: {
                                "data-framer-name": "Icon only - hover",
                                "data-highlight": true,
                                onMouseLeave: onMouseLeaveqpjrr2
                            },
                            EqKZSVRcz: {
                                "data-framer-name": "Small - no icon"
                            },
                            JIQlmXG3E: {
                                "data-framer-name": "Large - with icon"
                            },
                            jpYVtlPvM: {
                                "data-framer-name": "Icon only",
                                "data-highlight": true,
                                onMouseEnter: onMouseEntery74jci
                            },
                            LmeK3DXy0: {
                                "data-framer-name": "Small - with icon"
                            },
                            oc6EpmQ93: {
                                "data-framer-name": "BIg button"
                            }
                        }, baseVariant, gestureVariant),
                        children: [isDisplayed() && /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                        "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                        "--framer-font-size": "18px",
                                        "--framer-line-height": "1em",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-qicr92Taf-BAdt6St43))"
                                    },
                                    children: "Button"
                                })
                            }),
                            className: "framer-1scpvdc",
                            fonts: ["CUSTOM;Puffin Transit Bold"],
                            layoutDependency: layoutDependency,
                            layoutId: "ifBU7eiKy",
                            style: {
                                "--extracted-r6o4lv": "var(--variable-reference-qicr92Taf-BAdt6St43)",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                                "--variable-reference-qicr92Taf-BAdt6St43": qicr92Taf
                            },
                            text: EWzxxLsSp,
                            variants: {
                                "EqKZSVRcz-hover": {
                                    "--extracted-r6o4lv": "rgb(255, 255, 255)"
                                },
                                "oc6EpmQ93-hover": {
                                    "--extracted-r6o4lv": "rgb(255, 255, 255)"
                                },
                                "SaF3AtRH2-hover": {
                                    "--extracted-r6o4lv": "rgb(255, 255, 255)"
                                },
                                "SaF3AtRH2-pressed": {
                                    "--extracted-r6o4lv": "rgb(255, 255, 255)"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                "EqKZSVRcz-hover": {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                                "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))"
                                            },
                                            children: "Button"
                                        })
                                    })
                                },
                                "oc6EpmQ93-hover": {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                                "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                                "--framer-font-size": "18px",
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))"
                                            },
                                            children: "Button"
                                        })
                                    })
                                },
                                "SaF3AtRH2-hover": {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                                "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                                "--framer-font-size": "18px",
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))"
                                            },
                                            children: "Button"
                                        })
                                    })
                                },
                                "SaF3AtRH2-pressed": {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                                "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                                "--framer-font-size": "18px",
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, rgb(255, 255, 255))"
                                            },
                                            children: "Button"
                                        })
                                    })
                                },
                                EqKZSVRcz: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                                "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-qicr92Taf-BAdt6St43))"
                                            },
                                            children: "Button"
                                        })
                                    })
                                },
                                LmeK3DXy0: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                                "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                                "--framer-font-size": "14px",
                                                "--framer-line-height": "1.1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-qicr92Taf-BAdt6St43))"
                                            },
                                            children: "Button"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), isDisplayed1() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-uqx31b-container",
                                isAuthoredByUser: true,
                                layoutDependency: layoutDependency,
                                layoutId: "l0Wp5da3H-container",
                                nodeId: "l0Wp5da3H",
                                rendersWithMotion: true,
                                scopeId: "BAdt6St43",
                                children: /*#__PURE__*/ _jsx(Material, {
                                    color: "rgb(255, 255, 255)",
                                    height: "100%",
                                    iconSearch: "Home",
                                    iconSelection: "PhoneIphone",
                                    iconStyle15: "Filled",
                                    iconStyle2: "Filled",
                                    iconStyle7: "Filled",
                                    id: "l0Wp5da3H",
                                    layoutId: "l0Wp5da3H",
                                    mirrored: false,
                                    selectByList: true,
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        "oc6EpmQ93-hover": {
                                            color: "rgb(255, 255, 255)"
                                        },
                                        bToTb8PWg: {
                                            iconSelection: "Close",
                                            iconStyle15: "Rounded"
                                        },
                                        JIQlmXG3E: {
                                            color: "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))"
                                        },
                                        jpYVtlPvM: {
                                            color: Psd861PGB,
                                            iconSelection: F_7_e4f0K,
                                            iconStyle15: "Rounded"
                                        },
                                        LmeK3DXy0: {
                                            color: "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))"
                                        },
                                        oc6EpmQ93: {
                                            color: Psd861PGB,
                                            iconSelection: "ArrowForward"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-DRr9G.framer-v5zt70, .framer-DRr9G .framer-v5zt70 { display: block; }", ".framer-DRr9G.framer-s3svbn { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 56px; justify-content: center; padding: 16px 24px 16px 24px; position: relative; text-decoration: none; width: min-content; }", ".framer-DRr9G .framer-1scpvdc { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-DRr9G .framer-uqx31b-container { flex: none; height: 32px; position: relative; width: 32px; }", ".framer-DRr9G.framer-v-u1rd9y.framer-s3svbn { height: min-content; }", ".framer-DRr9G.framer-v-zd7s7d.framer-s3svbn { gap: 4px; height: min-content; padding: 12px 16px 12px 24px; }", ".framer-DRr9G.framer-v-zd7s7d .framer-uqx31b-container { height: 24px; width: 24px; }", ".framer-DRr9G.framer-v-7frf60.framer-s3svbn { height: 39px; padding: 16px; }", ".framer-DRr9G.framer-v-o64xxn.framer-s3svbn { height: 72px; width: 198px; }", ".framer-DRr9G.framer-v-o64xxn .framer-1scpvdc { flex: 1 0 0px; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", ".framer-DRr9G.framer-v-1f9gcuc.framer-s3svbn, .framer-DRr9G.framer-v-1gdfkb6.framer-s3svbn { height: 64px; width: 64px; }", ".framer-DRr9G.framer-v-1f9gcuc .framer-uqx31b-container, .framer-DRr9G.framer-v-1gdfkb6 .framer-uqx31b-container { height: 40px; width: 40px; }", '.framer-DRr9G[data-border="true"]::after, .framer-DRr9G [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 56
 * @framerIntrinsicWidth 110
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"JIQlmXG3E":{"layout":["auto","auto"]},"LmeK3DXy0":{"layout":["auto","auto"]},"EqKZSVRcz":{"layout":["auto","fixed"]},"oc6EpmQ93":{"layout":["fixed","fixed"]},"jpYVtlPvM":{"layout":["fixed","fixed"]},"bToTb8PWg":{"layout":["fixed","fixed"]},"coUjnK9qD":{"layout":["auto","fixed"]},"aLU1wlc2b":{"layout":["auto","fixed"]},"FkW8L_78C":{"layout":["auto","auto"]},"BdlryBI3c":{"layout":["auto","auto"]},"cxFGy1SkE":{"layout":["auto","auto"]},"fF9XBfwR6":{"layout":["auto","auto"]},"LxYtR0_gr":{"layout":["auto","fixed"]},"PpXQN8HcK":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"covLl01nh":"buttonLink","EWzxxLsSp":"buttonName","p7ZsoTYh9":"newTab","qicr92Taf":"textColor","LBCylfD1Z":"borderColor","NdU_7bDFg":"hoverColor","Bc1xkt19v":"pressedColor","Gu0ypBZYc":"backgroundColor","Psd861PGB":"iconColor","F_7_e4f0K":"icon"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerBAdt6St43 = withCSS(Component, css, "framer-DRr9G");
export default FramerBAdt6St43;
FramerBAdt6St43.displayName = "Call to action/Secondary button";
FramerBAdt6St43.defaultProps = {
    height: 56,
    width: 110
};
addPropertyControls(FramerBAdt6St43, {
    variant: {
        options: ["SaF3AtRH2", "JIQlmXG3E", "LmeK3DXy0", "EqKZSVRcz", "oc6EpmQ93", "jpYVtlPvM", "bToTb8PWg"],
        optionTitles: ["Large - no icon", "Large - with icon", "Small - with icon", "Small - no icon", "BIg button", "Icon only", "Icon only - hover"],
        title: "Variant",
        type: ControlType.Enum
    },
    covLl01nh: {
        title: "Button link",
        type: ControlType.Link
    },
    EWzxxLsSp: {
        defaultValue: "Button",
        placeholder: "Button",
        title: "Button name",
        type: ControlType.String
    },
    p7ZsoTYh9: {
        defaultValue: false,
        title: "New Tab",
        type: ControlType.Boolean
    },
    qicr92Taf: {
        defaultValue: "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
        title: "text-color",
        type: ControlType.Color
    },
    LBCylfD1Z: {
        defaultValue: {
            borderColor: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
            borderStyle: "solid",
            borderWidth: 2
        },
        title: "border-color",
        type: ControlType.Border
    },
    NdU_7bDFg: {
        defaultValue: "rgb(18, 69, 43)",
        title: "hover-color",
        type: ControlType.Color
    },
    Bc1xkt19v: {
        defaultValue: 'var(--token-0ef7fac7-2c02-40a6-9e44-9c2300205686, rgb(10, 41, 23)) /* {"name":"Green/900"} */',
        title: "pressed-color",
        type: ControlType.Color
    },
    Gu0ypBZYc: {
        defaultValue: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
        title: "background-color",
        type: ControlType.Color
    },
    Psd861PGB: {
        defaultValue: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
        title: "Icon color",
        type: ControlType.Color
    },
    F_7_e4f0K: MaterialControls ? .["iconSelection"] && { ...MaterialControls["iconSelection"],
        defaultValue: "Close",
        description: undefined,
        hidden: undefined,
        title: "icon"
    }
});
addFonts(FramerBAdt6St43, [{
    explicitInter: true,
    fonts: [{
        family: "Puffin Transit Bold",
        source: "custom",
        url: "https://framerusercontent.com/assets/GkunKxYt8QgoE68Kh0hyMBJoSI.ttf"
    }]
}, ...MaterialFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerBAdt6St43",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"covLl01nh\":\"buttonLink\",\"EWzxxLsSp\":\"buttonName\",\"p7ZsoTYh9\":\"newTab\",\"qicr92Taf\":\"textColor\",\"LBCylfD1Z\":\"borderColor\",\"NdU_7bDFg\":\"hoverColor\",\"Bc1xkt19v\":\"pressedColor\",\"Gu0ypBZYc\":\"backgroundColor\",\"Psd861PGB\":\"iconColor\",\"F_7_e4f0K\":\"icon\"}",
                "framerIntrinsicWidth": "110",
                "framerIntrinsicHeight": "56",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"fixed\"]},\"JIQlmXG3E\":{\"layout\":[\"auto\",\"auto\"]},\"LmeK3DXy0\":{\"layout\":[\"auto\",\"auto\"]},\"EqKZSVRcz\":{\"layout\":[\"auto\",\"fixed\"]},\"oc6EpmQ93\":{\"layout\":[\"fixed\",\"fixed\"]},\"jpYVtlPvM\":{\"layout\":[\"fixed\",\"fixed\"]},\"bToTb8PWg\":{\"layout\":[\"fixed\",\"fixed\"]},\"coUjnK9qD\":{\"layout\":[\"auto\",\"fixed\"]},\"aLU1wlc2b\":{\"layout\":[\"auto\",\"fixed\"]},\"FkW8L_78C\":{\"layout\":[\"auto\",\"auto\"]},\"BdlryBI3c\":{\"layout\":[\"auto\",\"auto\"]},\"cxFGy1SkE\":{\"layout\":[\"auto\",\"auto\"]},\"fF9XBfwR6\":{\"layout\":[\"auto\",\"auto\"]},\"LxYtR0_gr\":{\"layout\":[\"auto\",\"fixed\"]},\"PpXQN8HcK\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerColorSyntax": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./BAdt6St43.map