// Generated by Framer (518403a)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryEngine as r
} from "framer";
import {
    DatabaseCollection as t,
    DatabaseDictionaryIndex as a
} from "./Nl2YRKVR2-0.js";
import {
    getRichTextJsonResolver as m
} from "./Nl2YRKVR2-1.js";
let o = {
        cdvc3_lGn: {
            isNullable: !0,
            type: l.Boolean
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        gUerxdQTQ: {
            isNullable: !0,
            type: l.RichText
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        IPtcbcSXF: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        omMfHbnbT: {
            isNullable: !0,
            type: l.Enum
        },
        oWqwmNL1E: {
            isNullable: !0,
            type: l.Link
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        QMOfTLPse: {
            isNullable: !0,
            type: l.String
        },
        TlAQw2KCw: {
            isNullable: !0,
            type: l.String
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        },
        wrbIwpxEm: {
            isNullable: !0,
            type: l.Date
        }
    },
    c = ["id"],
    i = {
        type: 1
    },
    n = ["previousItemId"],
    s = ["nextItemId"],
    f = ["id", "QMOfTLPse"],
    d = ["QMOfTLPse", "id"],
    u = ["omMfHbnbT"],
    p = {
        type: 0
    },
    R = ["wrbIwpxEm"],
    w = ["TlAQw2KCw"],
    N = ["oWqwmNL1E"],
    h = ["IPtcbcSXF"],
    x = ["gUerxdQTQ"],
    g = ["cdvc3_lGn"],
    y = ["QMOfTLPse"],
    L = [],
    S = e => {
        let l = L[e];
        if (l) return l().then(e => e.default);
    },
    V = {},
    b = m(V),
    K = new r,
    U = {
        collectionByLocaleId: {
            default: new t({
                chunks: [new URL("./Nl2YRKVR2-chunk-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")],
                id: "6ca08bf4-1979-4d16-903e-02ba82ae5351default",
                indexes: [new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: c,
                    range: {
                        from: 0,
                        to: 337
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: n,
                    range: {
                        from: 337,
                        to: 673
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: s,
                    range: {
                        from: 673,
                        to: 1005
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: f,
                    range: {
                        from: 1005,
                        to: 1966
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: d,
                    range: {
                        from: 1966,
                        to: 2927
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: u,
                    range: {
                        from: 2927,
                        to: 3271
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: R,
                    range: {
                        from: 3271,
                        to: 3550
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: w,
                    range: {
                        from: 3550,
                        to: 4391
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: N,
                    range: {
                        from: 4391,
                        to: 5287
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: h,
                    range: {
                        from: 5287,
                        to: 10073
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: x,
                    range: {
                        from: 10073,
                        to: 10248
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: g,
                    range: {
                        from: 10248,
                        to: 10436
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: y,
                    range: {
                        from: 10436,
                        to: 11209
                    },
                    url: new URL("./Nl2YRKVR2-indexes-default-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: b,
                resolveVectorSetItem: S,
                schema: o
            }),
            xBEfqdO_2: new t({
                chunks: [new URL("./Nl2YRKVR2-chunk-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")],
                id: "6ca08bf4-1979-4d16-903e-02ba82ae5351xBEfqdO_2",
                indexes: [new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: c,
                    range: {
                        from: 0,
                        to: 337
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: n,
                    range: {
                        from: 337,
                        to: 673
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: s,
                    range: {
                        from: 673,
                        to: 1005
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: f,
                    range: {
                        from: 1005,
                        to: 1966
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: i,
                    collectionSchema: o,
                    fieldNames: d,
                    range: {
                        from: 1966,
                        to: 2927
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: u,
                    range: {
                        from: 2927,
                        to: 3271
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: R,
                    range: {
                        from: 3271,
                        to: 3550
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: w,
                    range: {
                        from: 3550,
                        to: 4391
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: N,
                    range: {
                        from: 4391,
                        to: 5287
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: h,
                    range: {
                        from: 5287,
                        to: 10073
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: x,
                    range: {
                        from: 10073,
                        to: 10248
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: g,
                    range: {
                        from: 10248,
                        to: 10436
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                }), new a({
                    collation: p,
                    collectionSchema: o,
                    fieldNames: y,
                    range: {
                        from: 10436,
                        to: 11209
                    },
                    url: new URL("./Nl2YRKVR2-indexes-xBEfqdO_2-0.framercms", "https://framerusercontent.com/modules/8q6e7HCQ0g8sD48MVCkt/93nkoidORPf7cCxpG9de/Nl2YRKVR2.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: b,
                resolveVectorSetItem: S,
                schema: o
            })
        },
        displayName: "Blog posts",
        id: "6ca08bf4-1979-4d16-903e-02ba82ae5351"
    };
export default U;
e(U, {
    omMfHbnbT: {
        defaultValue: "RxSlHAvDO",
        options: ["RxSlHAvDO", "FJS5Chr7S"],
        optionTitles: ["English", "French"],
        title: "Language",
        type: l.Enum
    },
    wrbIwpxEm: {
        title: "Date",
        type: l.Date
    },
    TlAQw2KCw: {
        defaultValue: "Blog article title",
        placeholder: "Blog article title",
        title: "Title",
        type: l.String
    },
    oWqwmNL1E: {
        title: "Link",
        type: l.Link
    },
    IPtcbcSXF: {
        title: "Image",
        type: l.ResponsiveImage
    },
    gUerxdQTQ: {
        defaultValue: "",
        title: "Content",
        type: l.RichText
    },
    cdvc3_lGn: {
        defaultValue: !0,
        title: "Is highligted",
        type: l.Boolean
    },
    QMOfTLPse: {
        preventLocalization: !0,
        title: "Slug",
        type: l.String
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/Nl2YRKVR2:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/Nl2YRKVR2:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const omMfHbnbTToDisplayName = (e, l) => {
    switch (l ? .fallback, e) {
        case "RxSlHAvDO":
            return "English";
        case "FJS5Chr7S":
            return "French";
        default:
            return "";
    }
};
export const enumToDisplayNameFunctions = {
    omMfHbnbT: omMfHbnbTToDisplayName
};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [r] = await K.query({
            from: {
                data: U,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "QMOfTLPse",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l);
        return r ? .QMOfTLPse;
    },
    async getRecordIdBySlug(e, l) {
        let [r] = await K.query({
            from: {
                data: U,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "QMOfTLPse",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l);
        return r ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerRecordIdKey": "id",
                "framerAutoSizeImages": "true",
                "framerEnumToDisplayNameUtils": "2",
                "framerData": "true",
                "framerColorSyntax": "false",
                "framerSlug": "QMOfTLPse",
                "framerCollectionId": "Nl2YRKVR2",
                "framerContractVersion": "1",
                "framerCollectionUtils": "1"
            }
        },
        "omMfHbnbTToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}