// Generated by Framer (6bfa4d3)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-rVEkR .framer-styles-preset-1djorfu:not(.rich-text-wrapper), .framer-rVEkR .framer-styles-preset-1djorfu.rich-text-wrapper a { --framer-link-current-text-color: #12452b; --framer-link-current-text-decoration: none; --framer-link-hover-text-color: #12452b; --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, #12452b); --framer-link-text-decoration: none; }"];
export const className = "framer-rVEkR";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}