// Generated by Framer (e010222)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = ['.framer-piZPG .framer-styles-preset-1lr4axb:not(.rich-text-wrapper), .framer-piZPG .framer-styles-preset-1lr4axb.rich-text-wrapper a { --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-77d7fb62-76a7-423c-abcb-db4d07b9f35c, #ff4a00) /* {"name":"Orange/500"} */; --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-77d7fb62-76a7-423c-abcb-db4d07b9f35c, #ff5500); --framer-link-text-decoration: none; }'];
export const className = "framer-piZPG";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}