// Generated by Framer (9cd6ca5)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Link,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    QzMzJeNeM: {
        hover: true
    }
};
const serializationHash = "framer-pV1A3";
const variantClassNames = {
    QzMzJeNeM: "framer-v-12hv5vx"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const numberToPixelString = value => {
    if (typeof value !== "number") return value;
    if (!Number.isFinite(value)) return undefined;
    return Math.max(0, value) + "px";
};
const transition1 = {
    duration: 0,
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    border,
    fontSize,
    height,
    highlightColor,
    id,
    link,
    linkColor,
    linkText,
    padding,
    width,
    ...props
}) => {
    return { ...props,
        feh1jIx7Y: padding ? ? props.feh1jIx7Y ? ? "4px 0px 3px 0px",
        IbrJWZntY: linkColor ? ? props.IbrJWZntY ? ? "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
        NXMI5DWra: highlightColor ? ? props.NXMI5DWra ? ? "var(--token-8f609ffa-e82c-4a0b-ab42-2f75d4124f29, rgb(254, 243, 207))",
        QQ_UujMt9: border ? ? props.QQ_UujMt9 ? ? {
            borderBottomWidth: 2,
            borderColor: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
            borderLeftWidth: 0,
            borderRightWidth: 0,
            borderStyle: "solid",
            borderTopWidth: 0
        },
        v2Tjf5P81: fontSize ? ? props.v2Tjf5P81 ? ? 16,
        zJ1TxWfwK: linkText ? ? props.zJ1TxWfwK ? ? "This is a text link",
        zYwGoCz0T: link ? ? props.zYwGoCz0T
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        QQ_UujMt9,
        zYwGoCz0T,
        zJ1TxWfwK,
        IbrJWZntY,
        NXMI5DWra,
        v2Tjf5P81,
        feh1jIx7Y,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "QzMzJeNeM",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: zYwGoCz0T,
                    motionChild: true,
                    nodeId: "QzMzJeNeM",
                    openInNewTab: false,
                    scopeId: "JJRB3lqQF",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-12hv5vx",className,classNames)} framer-s03orq`,
                        "data-border": true,
                        "data-framer-name": "Text link",
                        layoutDependency: layoutDependency,
                        layoutId: "QzMzJeNeM",
                        ref: refBinding,
                        style: {
                            "--border-bottom-width": (QQ_UujMt9.borderBottomWidth ? ? QQ_UujMt9.borderWidth) + "px",
                            "--border-color": QQ_UujMt9.borderColor,
                            "--border-left-width": (QQ_UujMt9.borderLeftWidth ? ? QQ_UujMt9.borderWidth) + "px",
                            "--border-right-width": (QQ_UujMt9.borderRightWidth ? ? QQ_UujMt9.borderWidth) + "px",
                            "--border-style": QQ_UujMt9.borderStyle,
                            "--border-top-width": (QQ_UujMt9.borderTopWidth ? ? QQ_UujMt9.borderWidth) + "px",
                            "--pgu86w": numberToPixelString(feh1jIx7Y),
                            ...style
                        },
                        ...addPropertyOverrides({
                            "QzMzJeNeM-hover": {
                                "data-framer-name": undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-5d2nx0",
                            "data-framer-name": "highlight",
                            layoutDependency: layoutDependency,
                            layoutId: "fNHTI4Kso",
                            style: {
                                backgroundColor: "var(--token-8f609ffa-e82c-4a0b-ab42-2f75d4124f29, rgb(254, 243, 207))",
                                opacity: 0
                            },
                            variants: {
                                "QzMzJeNeM-hover": {
                                    backgroundColor: NXMI5DWra,
                                    opacity: 1
                                }
                            }
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                        "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                        "--framer-font-size": "calc(var(--variable-reference-v2Tjf5P81-JJRB3lqQF) * 1px)",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-IbrJWZntY-JJRB3lqQF))"
                                    },
                                    children: "This is a text link"
                                })
                            }),
                            className: "framer-88xjd2",
                            fonts: ["CUSTOM;Puffin Transit Bold"],
                            layoutDependency: layoutDependency,
                            layoutId: "brvzdq2NI",
                            style: {
                                "--extracted-r6o4lv": "var(--variable-reference-IbrJWZntY-JJRB3lqQF)",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline",
                                "--variable-reference-IbrJWZntY-JJRB3lqQF": IbrJWZntY,
                                "--variable-reference-v2Tjf5P81-JJRB3lqQF": v2Tjf5P81
                            },
                            text: zJ1TxWfwK,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-pV1A3.framer-s03orq, .framer-pV1A3 .framer-s03orq { display: block; }", ".framer-pV1A3.framer-12hv5vx { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: var(--pgu86w); position: relative; text-decoration: none; width: min-content; }", ".framer-pV1A3 .framer-5d2nx0 { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; z-index: 0; }", ".framer-pV1A3 .framer-88xjd2 { flex: none; height: 20px; position: relative; white-space: pre; width: auto; }", '.framer-pV1A3[data-border="true"]::after, .framer-pV1A3 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 27
 * @framerIntrinsicWidth 131
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"muO_ZGlS4":{"layout":["auto","auto"]}}}
 * @framerVariables {"QQ_UujMt9":"border","zYwGoCz0T":"link","zJ1TxWfwK":"linkText","IbrJWZntY":"linkColor","NXMI5DWra":"highlightColor","v2Tjf5P81":"fontSize","feh1jIx7Y":"padding"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerJJRB3lqQF = withCSS(Component, css, "framer-pV1A3");
export default FramerJJRB3lqQF;
FramerJJRB3lqQF.displayName = "Call to action/Text link";
FramerJJRB3lqQF.defaultProps = {
    height: 27,
    width: 131
};
addPropertyControls(FramerJJRB3lqQF, {
    QQ_UujMt9: {
        defaultValue: {
            borderBottomWidth: 2,
            borderColor: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
            borderLeftWidth: 0,
            borderRightWidth: 0,
            borderStyle: "solid",
            borderTopWidth: 0
        },
        title: "Border",
        type: ControlType.Border
    },
    zYwGoCz0T: {
        title: "Link",
        type: ControlType.Link
    },
    zJ1TxWfwK: {
        defaultValue: "This is a text link",
        description: "",
        displayTextArea: false,
        placeholder: "This is a text link",
        title: "Link text",
        type: ControlType.String
    },
    IbrJWZntY: {
        defaultValue: "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
        title: "link color",
        type: ControlType.Color
    },
    NXMI5DWra: {
        defaultValue: 'var(--token-8f609ffa-e82c-4a0b-ab42-2f75d4124f29, rgb(254, 243, 207)) /* {"name":"Yellow/100"} */',
        title: "highlight color",
        type: ControlType.Color
    },
    v2Tjf5P81: {
        defaultValue: 16,
        title: "Font Size",
        type: ControlType.Number
    },
    feh1jIx7Y: {
        defaultValue: "4px 0px 3px 0px",
        title: "Padding",
        type: ControlType.Padding
    }
});
addFonts(FramerJJRB3lqQF, [{
    explicitInter: true,
    fonts: [{
        family: "Puffin Transit Bold",
        source: "custom",
        url: "https://framerusercontent.com/assets/GkunKxYt8QgoE68Kh0hyMBJoSI.ttf"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerJJRB3lqQF",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerVariables": "{\"QQ_UujMt9\":\"border\",\"zYwGoCz0T\":\"link\",\"zJ1TxWfwK\":\"linkText\",\"IbrJWZntY\":\"linkColor\",\"NXMI5DWra\":\"highlightColor\",\"v2Tjf5P81\":\"fontSize\",\"feh1jIx7Y\":\"padding\"}",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "131",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"muO_ZGlS4\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "27",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./JJRB3lqQF.map