// Generated by Framer (2a6858f)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = ['.framer-xd450 .framer-styles-preset-63h3dw:not(.rich-text-wrapper), .framer-xd450 .framer-styles-preset-63h3dw.rich-text-wrapper a { --framer-link-current-text-color: var(--token-d0e27c3b-2c2d-4b5b-88cb-4a400a19863e, #a800b0) /* {"name":"Purple/600"} */; --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: var(--token-a6211630-9297-4c0c-a5ad-28e91b5e78d8, #790080) /* {"name":"Purple/700"} */; --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-d0e27c3b-2c2d-4b5b-88cb-4a400a19863e, #a800b0); --framer-link-text-decoration: none; }'];
export const className = "framer-xd450";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}