// Generated by Framer (f0648f9)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    Link,
    RichText,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import IconsRegularIcon from "https://framerusercontent.com/modules/aPzlov2UwsjgN1KxqblG/7aU0fzSdXgnegLrghsKl/T5oWNqJOn.js";
const IconsRegularIconFonts = getFonts(IconsRegularIcon);
const enabledGestures = {
    HkENQNAbA: {
        hover: true
    }
};
const cycleOrder = ["HkENQNAbA", "EOmK4cLcz"];
const serializationHash = "framer-jttvz";
const variantClassNames = {
    EOmK4cLcz: "framer-v-nxxqky",
    HkENQNAbA: "framer-v-u5eww8"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const SSORw_6qh = undefined;
const TQT_5ALbw = undefined;
const c1n3j9ouP = undefined;
const EyNj553S6 = undefined;
const IWR5xmWEa = undefined;
const transition1 = {
    delay: 0,
    duration: .3,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const matchVariant = (...args) => {
    for (const arg of args) {
        if (arg && typeof arg === "string") return arg;
    }
    return undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    "Mobile menu item": "EOmK4cLcz",
    Element: "HkENQNAbA"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    height,
    iconColor,
    id,
    link,
    name1,
    textColor,
    width,
    ...props
}) => {
    return { ...props,
        c1n3j9ouP: iconColor ? ? props.c1n3j9ouP ? ? "rgb(255, 255, 255)",
        EyNj553S6: textColor ? ? props.EyNj553S6 ? ? "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
        IWR5xmWEa: name1 ? ? props.IWR5xmWEa ? ? "About",
        SSORw_6qh: click ? ? props.SSORw_6qh,
        TQT_5ALbw: link ? ? props.TQT_5ALbw,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "HkENQNAbA"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        IWR5xmWEa,
        TQT_5ALbw,
        SSORw_6qh,
        EyNj553S6,
        c1n3j9ouP,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "HkENQNAbA",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap14xysw8 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (SSORw_6qh) {
            const res = await SSORw_6qh(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "EOmK4cLcz") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: TQT_5ALbw,
                    motionChild: true,
                    nodeId: "HkENQNAbA",
                    openInNewTab: false,
                    scopeId: "Gbo35i4e4",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-u5eww8",className,classNames)} framer-f1fl8g`,
                        "data-framer-name": "Element",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "HkENQNAbA",
                        onTap: onTap14xysw8,
                        ref: refBinding,
                        style: {
                            backgroundColor: "rgba(255, 255, 255, 0)",
                            borderBottomLeftRadius: 32,
                            borderBottomRightRadius: 32,
                            borderTopLeftRadius: 32,
                            borderTopRightRadius: 32,
                            ...style
                        },
                        variants: {
                            "HkENQNAbA-hover": {
                                backgroundColor: "rgba(255, 255, 255, 0.32)"
                            }
                        },
                        ...addPropertyOverrides({
                            "HkENQNAbA-hover": {
                                "data-framer-name": undefined
                            },
                            EOmK4cLcz: {
                                "data-framer-name": "Mobile menu item"
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-1yutufu",
                            layoutDependency: layoutDependency,
                            layoutId: "qG7PImadT",
                            children: [isDisplayed() && /*#__PURE__*/ _jsx(ComponentViewportProvider, { ...addPropertyOverrides({
                                    EOmK4cLcz: {
                                        height: 32,
                                        width: "32px",
                                        y: (componentViewport ? .y || 0) + 10 + (((componentViewport ? .height || 52) - 20 - 32) / 2 + 0 + 0) + 0
                                    }
                                }, baseVariant, gestureVariant),
                                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                    className: "framer-1v7i9sl-container",
                                    "data-framer-name": "Mobile icon",
                                    layoutDependency: layoutDependency,
                                    layoutId: "onvgPdmyr-container",
                                    name: "Mobile icon",
                                    nodeId: "onvgPdmyr",
                                    rendersWithMotion: true,
                                    scopeId: "Gbo35i4e4",
                                    children: /*#__PURE__*/ _jsx(IconsRegularIcon, {
                                        height: "100%",
                                        id: "onvgPdmyr",
                                        layoutId: "onvgPdmyr",
                                        name: "Mobile icon",
                                        RJu_Yah9V: c1n3j9ouP,
                                        style: {
                                            height: "100%",
                                            width: "100%"
                                        },
                                        variant: matchVariant("mYloXy5WX"),
                                        width: "100%",
                                        zf7VgQjvl: "rgb(255, 255, 255)"
                                    })
                                })
                            }), /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        dir: "auto",
                                        style: {
                                            "--font-selector": "Q1VTVE9NVjI7UHVmZmluIFRyYW5zaXQgU2VtaUJvbGQ=",
                                            "--framer-font-family": '"Puffin Transit SemiBold", "Puffin Transit SemiBold Placeholder", sans-serif',
                                            "--framer-font-weight": "600",
                                            "--framer-line-height": "16px",
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-EyNj553S6-Gbo35i4e4))"
                                        },
                                        children: "About"
                                    })
                                }),
                                className: "framer-1b3vbgc",
                                fonts: ["CUSTOMV2;Puffin Transit SemiBold"],
                                layoutDependency: layoutDependency,
                                layoutId: "o2hcdaOiX",
                                style: {
                                    "--extracted-r6o4lv": "var(--variable-reference-EyNj553S6-Gbo35i4e4)",
                                    "--variable-reference-EyNj553S6-Gbo35i4e4": EyNj553S6
                                },
                                text: IWR5xmWEa,
                                verticalAlignment: "top",
                                withExternalLayout: true,
                                ...addPropertyOverrides({
                                    EOmK4cLcz: {
                                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                                            children: /*#__PURE__*/ _jsx(motion.p, {
                                                dir: "auto",
                                                style: {
                                                    "--font-selector": "Q1VTVE9NVjI7UHVmZmluIFRyYW5zaXQgU2VtaUJvbGQ=",
                                                    "--framer-font-family": '"Puffin Transit SemiBold", "Puffin Transit SemiBold Placeholder", sans-serif',
                                                    "--framer-font-size": "18px",
                                                    "--framer-font-weight": "600",
                                                    "--framer-line-height": "16px",
                                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-EyNj553S6-Gbo35i4e4))"
                                                },
                                                children: "About"
                                            })
                                        })
                                    }
                                }, baseVariant, gestureVariant)
                            })]
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-jttvz.framer-f1fl8g, .framer-jttvz .framer-f1fl8g { display: block; }", ".framer-jttvz.framer-u5eww8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 12px 20px 12px 20px; position: relative; text-decoration: none; width: min-content; }", ".framer-jttvz .framer-1yutufu { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: auto; }", ".framer-jttvz .framer-1v7i9sl-container { flex: none; height: 32px; position: relative; width: 32px; }", ".framer-jttvz .framer-1b3vbgc { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-jttvz.framer-v-nxxqky.framer-u5eww8 { padding: 10px 0px 10px 0px; }", ".framer-jttvz.framer-v-nxxqky .framer-1yutufu { gap: 8px; justify-content: flex-start; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 87
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"EOmK4cLcz":{"layout":["auto","auto"]},"L7dS5N40G":{"layout":["auto","auto"]}}}
 * @framerVariables {"IWR5xmWEa":"name1","TQT_5ALbw":"link","SSORw_6qh":"click","EyNj553S6":"textColor","c1n3j9ouP":"iconColor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerGbo35i4e4 = withCSS(Component, css, "framer-jttvz");
export default FramerGbo35i4e4;
FramerGbo35i4e4.displayName = "Shared elements/Menu item";
FramerGbo35i4e4.defaultProps = {
    height: 40,
    width: 87
};
addPropertyControls(FramerGbo35i4e4, {
    variant: {
        options: ["HkENQNAbA", "EOmK4cLcz"],
        optionTitles: ["Element", "Mobile menu item"],
        title: "Variant",
        type: ControlType.Enum
    },
    IWR5xmWEa: {
        defaultValue: "About",
        displayTextArea: false,
        title: "Name",
        type: ControlType.String
    },
    TQT_5ALbw: {
        title: "Link",
        type: ControlType.Link
    },
    SSORw_6qh: {
        title: "Click",
        type: ControlType.EventHandler
    },
    EyNj553S6: {
        defaultValue: 'var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)) /* {"name":"Green/800"} */',
        title: "text-color",
        type: ControlType.Color
    },
    c1n3j9ouP: {
        defaultValue: "rgb(255, 255, 255)",
        title: "Icon Color",
        type: ControlType.Color
    }
});
addFonts(FramerGbo35i4e4, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Puffin Transit SemiBold",
        source: "custom",
        style: "normal",
        uiFamilyName: "Puffin Transit",
        url: "https://framerusercontent.com/assets/P8JM7v1p4kStalfdPuKbi1WeVKo.ttf",
        weight: "600"
    }]
}, ...IconsRegularIconFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerGbo35i4e4",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"EOmK4cLcz\":{\"layout\":[\"auto\",\"auto\"]},\"L7dS5N40G\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"IWR5xmWEa\":\"name1\",\"TQT_5ALbw\":\"link\",\"SSORw_6qh\":\"click\",\"EyNj553S6\":\"textColor\",\"c1n3j9ouP\":\"iconColor\"}",
                "framerIntrinsicHeight": "40",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "87"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./Gbo35i4e4.map