// Generated by Framer (0784c89)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useOnVariantChange,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    wXoViLAkO: {
        hover: true
    }
};
const cycleOrder = ["UAd2XP7oi", "joBmOedT1", "QsaQQfWIx", "VVmjKXU9s", "wXoViLAkO"];
const serializationHash = "framer-CkjDL";
const variantClassNames = {
    joBmOedT1: "framer-v-o94y16",
    QsaQQfWIx: "framer-v-1ax8509",
    UAd2XP7oi: "framer-v-1fr9ng1",
    VVmjKXU9s: "framer-v-1flfanw",
    wXoViLAkO: "framer-v-1whhirr"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: 0,
    duration: .3,
    ease: [0, 0, 1, 1],
    type: "tween"
};
const transition2 = {
    duration: 0,
    type: "tween"
};
const transition3 = {
    delay: 0,
    duration: 15,
    ease: [0, 0, 1, 1],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Load: "joBmOedT1",
    Loaded: "VVmjKXU9s",
    Loading: "QsaQQfWIx",
    Selected: "UAd2XP7oi",
    Unselected: "wXoViLAkO"
};
const getProps = ({
    height,
    id,
    label,
    next,
    tap,
    width,
    ...props
}) => {
    return { ...props,
        d4wsynxz1: tap ? ? props.d4wsynxz1,
        KWa95rrxy: label ? ? props.KWa95rrxy ? ? "Label",
        UcJ5sUgF4: next ? ? props.UcJ5sUgF4,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "UAd2XP7oi"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        KWa95rrxy,
        d4wsynxz1,
        UcJ5sUgF4,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "UAd2XP7oi",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onAppearzs1myw = activeVariantCallback(async (...args) => {
        setVariant("QsaQQfWIx");
    });
    const onAppear102gyjx = activeVariantCallback(async (...args) => {
        await delay(() => setVariant("VVmjKXU9s"), 15e3);
    });
    const onAppear59c9ul = activeVariantCallback(async (...args) => {
        if (UcJ5sUgF4) {
            const res = await UcJ5sUgF4(...args);
            if (res === false) return false;
        }
        setVariant("wXoViLAkO");
    });
    const onTap1psuw38 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (d4wsynxz1) {
            const res = await d4wsynxz1(...args);
            if (res === false) return false;
        }
    });
    useOnVariantChange(baseVariant, {
        joBmOedT1: onAppearzs1myw,
        QsaQQfWIx: onAppear102gyjx,
        VVmjKXU9s: onAppear59c9ul
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                ...addPropertyOverrides({
                    wXoViLAkO: {
                        value: transition2
                    }
                }, baseVariant, gestureVariant),
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1fr9ng1", className, classNames),
                    "data-framer-name": "Selected",
                    layoutDependency: layoutDependency,
                    layoutId: "UAd2XP7oi",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-6edfe603-67ec-4af1-844d-a7f5e4f92a13, rgb(255, 247, 229))",
                        borderBottomLeftRadius: 8,
                        borderBottomRightRadius: 8,
                        borderTopLeftRadius: 8,
                        borderTopRightRadius: 8,
                        ...style
                    },
                    variants: {
                        "wXoViLAkO-hover": {
                            backgroundColor: "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))"
                        },
                        wXoViLAkO: {
                            backgroundColor: "rgba(27, 101, 57, 0.64)"
                        }
                    },
                    ...addPropertyOverrides({
                        "wXoViLAkO-hover": {
                            "data-framer-name": undefined
                        },
                        joBmOedT1: {
                            "data-framer-name": "Load",
                            "data-highlight": true
                        },
                        QsaQQfWIx: {
                            "data-framer-name": "Loading",
                            "data-highlight": true
                        },
                        VVmjKXU9s: {
                            "data-framer-name": "Loaded",
                            "data-highlight": true
                        },
                        wXoViLAkO: {
                            "data-framer-name": "Unselected",
                            "data-highlight": true,
                            onTap: onTap1psuw38
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                    "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                    "--framer-font-size": "14px",
                                    "--framer-line-height": "1em",
                                    "--framer-text-alignment": "left",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43)))"
                                },
                                children: "Label"
                            })
                        }),
                        className: "framer-1kjoxlx",
                        fonts: ["CUSTOM;Puffin Transit Bold"],
                        layoutDependency: layoutDependency,
                        layoutId: "NSxhC0LWN",
                        style: {
                            "--extracted-r6o4lv": "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: KWa95rrxy,
                        variants: {
                            wXoViLAkO: {
                                "--extracted-r6o4lv": "var(--token-6edfe603-67ec-4af1-844d-a7f5e4f92a13, rgb(255, 247, 229))"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            wXoViLAkO: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        style: {
                                            "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                            "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                            "--framer-font-size": "14px",
                                            "--framer-line-height": "1em",
                                            "--framer-text-alignment": "left",
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-6edfe603-67ec-4af1-844d-a7f5e4f92a13, rgb(255, 247, 229)))"
                                        },
                                        children: "Label"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1yslqxo",
                        "data-framer-name": "Loading-box",
                        layoutDependency: layoutDependency,
                        layoutId: "Ke15p2zab",
                        children: /*#__PURE__*/ _jsx(Transition, {
                            value: transition3,
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-1n7ndea",
                                layoutDependency: layoutDependency,
                                layoutId: "hXqJXAMgn",
                                style: {
                                    backgroundColor: "rgb(243, 255, 248)",
                                    borderTopRightRadius: 2
                                },
                                variants: {
                                    QsaQQfWIx: {
                                        backgroundColor: "var(--token-34858155-7e86-47cc-89e9-324891617319, rgb(219, 0, 230))"
                                    },
                                    VVmjKXU9s: {
                                        backgroundColor: "var(--token-6edfe603-67ec-4af1-844d-a7f5e4f92a13, rgb(255, 247, 229))"
                                    }
                                }
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-CkjDL.framer-19tbjwj, .framer-CkjDL .framer-19tbjwj { display: block; }", ".framer-CkjDL.framer-1fr9ng1 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: hidden; padding: 12px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-CkjDL .framer-1kjoxlx { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-CkjDL .framer-1yslqxo { align-content: flex-start; align-items: flex-start; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 5px; justify-content: flex-start; left: 0px; overflow: hidden; padding: 0px; position: absolute; right: 0px; z-index: 1; }", ".framer-CkjDL .framer-1n7ndea { flex: none; height: 100%; overflow: hidden; position: relative; width: 0%; will-change: var(--framer-will-change-override, transform); }", ".framer-CkjDL.framer-v-o94y16 .framer-1yslqxo { right: 61px; }", ".framer-CkjDL.framer-v-1ax8509 .framer-1n7ndea, .framer-CkjDL.framer-v-1flfanw .framer-1n7ndea { width: 100%; }", ".framer-CkjDL.framer-v-1flfanw .framer-1yslqxo { padding: 0px 3px 0px 3px; }", ".framer-CkjDL.framer-v-1whhirr.framer-1fr9ng1 { cursor: pointer; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 61.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"joBmOedT1":{"layout":["auto","fixed"]},"QsaQQfWIx":{"layout":["auto","fixed"]},"VVmjKXU9s":{"layout":["auto","fixed"]},"wXoViLAkO":{"layout":["auto","fixed"]},"QBi1xNxMH":{"layout":["auto","fixed"]}}}
 * @framerVariables {"KWa95rrxy":"label","d4wsynxz1":"tap","UcJ5sUgF4":"next"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FrameraPJmBH8Ut = withCSS(Component, css, "framer-CkjDL");
export default FrameraPJmBH8Ut;
FrameraPJmBH8Ut.displayName = "Victorien/Slideshow Button";
FrameraPJmBH8Ut.defaultProps = {
    height: 40,
    width: 61.5
};
addPropertyControls(FrameraPJmBH8Ut, {
    variant: {
        options: ["UAd2XP7oi", "joBmOedT1", "QsaQQfWIx", "VVmjKXU9s", "wXoViLAkO"],
        optionTitles: ["Selected", "Load", "Loading", "Loaded", "Unselected"],
        title: "Variant",
        type: ControlType.Enum
    },
    KWa95rrxy: {
        defaultValue: "Label",
        displayTextArea: false,
        title: "Label",
        type: ControlType.String
    },
    d4wsynxz1: {
        title: "Tap",
        type: ControlType.EventHandler
    },
    UcJ5sUgF4: {
        title: "Next",
        type: ControlType.EventHandler
    }
});
addFonts(FrameraPJmBH8Ut, [{
    explicitInter: true,
    fonts: [{
        family: "Puffin Transit Bold",
        source: "custom",
        url: "https://framerusercontent.com/assets/GkunKxYt8QgoE68Kh0hyMBJoSI.ttf"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FrameraPJmBH8Ut",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "40",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "61.5",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"fixed\"]},\"joBmOedT1\":{\"layout\":[\"auto\",\"fixed\"]},\"QsaQQfWIx\":{\"layout\":[\"auto\",\"fixed\"]},\"VVmjKXU9s\":{\"layout\":[\"auto\",\"fixed\"]},\"wXoViLAkO\":{\"layout\":[\"auto\",\"fixed\"]},\"QBi1xNxMH\":{\"layout\":[\"auto\",\"fixed\"]}}}",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"KWa95rrxy\":\"label\",\"d4wsynxz1\":\"tap\",\"UcJ5sUgF4\":\"next\"}",
                "framerColorSyntax": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./aPJmBH8Ut.map