// Generated by Framer (99bc0fd)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import SharedElementsCursor from "https://framerusercontent.com/modules/SD5d7tCSMn9YkgwiQfNT/Wh5W1Un7C4XN03eyjwGC/V1oZgUIZe.js";
import * as localizedValues from "./ZHJDCsOow-0.js";
const SharedElementsCursorFonts = getFonts(SharedElementsCursor);
const enabledGestures = {
    rxmmSQOQO: {
        hover: true
    }
};
const serializationHash = "framer-3E3Bh";
const variantClassNames = {
    rxmmSQOQO: "framer-v-j03uc1"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants === null || variants === void 0 ? void 0 : variants.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const valuesByLocaleId = {
    xBEfqdO_2: localizedValues
};
const getLocalizedValue = (key, locale) => {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) {
                return value;
            }
        }
        locale = locale.fallback;
    }
};
const transition1 = {
    duration: 0,
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value !== null && value !== void 0 ? value : config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        bMssCJ5i8: click !== null && click !== void 0 ? click : props.bMssCJ5i8
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        bMssCJ5i8,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "rxmmSQOQO",
        enabledGestures,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTapog78q1 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (bMssCJ5i8) {
            const res = await bMssCJ5i8(...args);
            if (res === false) return false;
        }
    });
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const sharedStyleClassNames = [];
    const componentViewport = useComponentViewport();
    var _getLocalizedValue;
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(serializationHash, ...sharedStyleClassNames, "framer-j03uc1", className, classNames),
                    "data-framer-name": "Variant 1",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "rxmmSQOQO",
                    onTap: onTapog78q1,
                    ref: ref !== null && ref !== void 0 ? ref : ref1,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        "rxmmSQOQO-hover": {
                            "data-framer-name": undefined
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-qto5ed",
                        layoutDependency: layoutDependency,
                        layoutId: "ajy91lFO0",
                        style: {
                            backgroundColor: "rgba(0, 0, 0, 0)",
                            borderBottomLeftRadius: 40,
                            borderBottomRightRadius: 40,
                            borderTopLeftRadius: 40,
                            borderTopRightRadius: 40
                        },
                        variants: {
                            "rxmmSQOQO-hover": {
                                backgroundColor: "var(--token-d1a4bbc5-2081-49ff-9c77-609155bd7847, rgb(18, 69, 43))"
                            }
                        },
                        children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 40,
                            width: "40px",
                            y: ((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + (0 + (((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 40) - 0 - 40) / 2) + 0,
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-1r2tyla-container",
                                layoutDependency: layoutDependency,
                                layoutId: "EwhdfM0Ou-container",
                                children: /*#__PURE__*/ _jsx(SharedElementsCursor, {
                                    height: "100%",
                                    id: "EwhdfM0Ou",
                                    IfOylP2jC: {
                                        borderColor: 'var(--token-6edfe603-67ec-4af1-844d-a7f5e4f92a13, rgb(255, 247, 229)) /* {"name":"Yellow/10"} */',
                                        borderStyle: "solid",
                                        borderWidth: 2
                                    },
                                    layoutId: "EwhdfM0Ou",
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    uSS3wjZ48: "var(--token-6edfe603-67ec-4af1-844d-a7f5e4f92a13, rgb(255, 247, 229))",
                                    variant: "wbs4kEBcS",
                                    width: "100%"
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: (_getLocalizedValue = getLocalizedValue("v0", activeLocale)) !== null && _getLocalizedValue !== void 0 ? _getLocalizedValue : /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                style: {
                                    "--font-selector": "Q1VTVE9NO1B1ZmZpbiBUcmFuc2l0IEJvbGQ=",
                                    "--framer-font-family": '"Puffin Transit Bold", "Puffin Transit Bold Placeholder", sans-serif',
                                    "--framer-font-size": "14px",
                                    "--framer-letter-spacing": "0px",
                                    "--framer-line-height": "1.3em",
                                    "--framer-text-alignment": "left",
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-6edfe603-67ec-4af1-844d-a7f5e4f92a13, rgb(255, 247, 229)))"
                                },
                                children: "Next"
                            })
                        }),
                        className: "framer-ctz31w",
                        "data-framer-name": "Paragraph",
                        fonts: ["CUSTOM;Puffin Transit Bold"],
                        layoutDependency: layoutDependency,
                        layoutId: "XoRlKw9LX",
                        style: {
                            "--extracted-r6o4lv": "var(--token-6edfe603-67ec-4af1-844d-a7f5e4f92a13, rgb(255, 247, 229))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-3E3Bh.framer-1c8by7x, .framer-3E3Bh .framer-1c8by7x { display: block; }", ".framer-3E3Bh.framer-j03uc1 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 474px; }", ".framer-3E3Bh .framer-qto5ed { aspect-ratio: 1 / 1; flex: none; height: 40px; overflow: visible; position: relative; width: var(--framer-aspect-ratio-supported, 40px); }", ".framer-3E3Bh .framer-1r2tyla-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }", ".framer-3E3Bh .framer-ctz31w { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-3E3Bh.framer-j03uc1 { gap: 0px; } .framer-3E3Bh.framer-j03uc1 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-3E3Bh.framer-j03uc1 > :first-child { margin-left: 0px; } .framer-3E3Bh.framer-j03uc1 > :last-child { margin-right: 0px; } }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 474
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"pVDxWEPUB":{"layout":["fixed","auto"]}}}
 * @framerVariables {"bMssCJ5i8":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerZHJDCsOow = withCSS(Component, css, "framer-3E3Bh");
export default FramerZHJDCsOow;
FramerZHJDCsOow.displayName = "Call to action/Icon link";
FramerZHJDCsOow.defaultProps = {
    height: 40,
    width: 474
};
addPropertyControls(FramerZHJDCsOow, {
    bMssCJ5i8: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerZHJDCsOow, [{
    explicitInter: true,
    fonts: [{
        family: "Puffin Transit Bold",
        source: "custom",
        url: "https://framerusercontent.com/assets/GkunKxYt8QgoE68Kh0hyMBJoSI.ttf"
    }]
}, ...SharedElementsCursorFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerZHJDCsOow",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "40",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"pVDxWEPUB\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerVariables": "{\"bMssCJ5i8\":\"click\"}",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "474",
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./ZHJDCsOow.map