// Generated by Framer (c8e5bf6)
const valuesByLocaleId = {
    xBEfqdO_2: {
        v0: "Transit - la meilleure appli pour le bus, le m\xe9tro et le train",
        v1: "Transit r\xeave d’un futur sans voitures et de villes qui donnent envie d’y vivre. Tout \xe7a commence par des transports collectifs durables — \xe7a tombe bien, notre appli vous aide \xe0 les trouver pour que vous ayez plaisir \xe0 y embarquer."
    }
};

function getLocalizedValue(key, locale) {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) return value;
        }
        locale = locale.fallback;
    }
}
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "1panbyv",
            mediaQuery: "(min-width: 1024px)"
        }, {
            hash: "ulm1p6",
            mediaQuery: "(min-width: 650px) and (max-width: 1023.98px)"
        }, {
            hash: "1qhpnac",
            mediaQuery: "(max-width: 649.98px)"
        }],
        description: getLocalizedValue("v1", activeLocale) ? ? "The world's most accurate transit app. Never miss a bus or train again in our 1000+ supported cities, including New York, Paris, London, Montreal and more",
        elements: {
            CKko3s8eP: "cardone",
            Fj1FVwxPx: "bloglist-en",
            G9tfvEcJm: "blog",
            sdwj6haKK: "threshold",
            TGImTZA6O: "cardtwo",
            tLaLHUJpX: "cardthree",
            zA2O5j492: "bloglist-fr",
            ZzOGsI7mQ: "cities"
        },
        framerSearch: {
            index: true
        },
        robots: "max-image-preview:large",
        serializationId: "framer-leHKb",
        socialImage: "https://framerusercontent.com/assets/e4QWm2cmnzSUJrs7eJ0D9PswUE.png",
        title: getLocalizedValue("v0", activeLocale) ? ? "Transit - the best app for buses and trains",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}